spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booksdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379
    cache:
      time-to-live: 3600
