version: '3.8'

services:
  db:
    image: postgres:13
    container_name: contactlist_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contactlist
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: contactlist_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contactlist
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
